import type { Metadata } from 'next';
import './globals.css';
import { inter, lexendDeca } from './fonts';

export const metadata: Metadata = {
  title: 'MLSA | Sri-Lanka',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      {/* favicon */}
      <head>
        <link rel='icon' href={'/logo.png'} type='image/<generated>' sizes='<generated>' />
      </head>
      <body className={`${inter.variable} ${lexendDeca.variable} font-inter`}>{children}</body>
    </html>
  );
}
